### ISSUE TITLE
liked songs page

### ISSUE THREAD

**Issue by phishy** [chelsey-g/spotify-clone#11]
## Objective

Replicate the following Spotify page.

## Lessons

- using React Router to add Routes/Links
- using `fetch` to retrieve data from Spotify's REST API
- using a Page/View (LikedSongsPage/LikedSongsView) design pattern to isolate data fetching logic from view rendering logic
- adding properties to existing components

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/26844/187728749-94e14c44-4edd-4f07-8ab7-c756116de408.png">

**Comment by chelsey-g** [comment]
As of right now, there are only a few more edits/additions I need to make to this page for completion...

- [ ]  add artist name under track name
- [ ] fix index so it is in order
- [ ] fix the date column with a more appealing look
- [ ] add user name and profile picture (header)
- [ ] add total playlist song (header)
