### ISSUE TITLE
layout does not extend to the edge of the screen

### ISSUE THREAD

**Issue by phishy** [chelsey-g/spotify-clone#3]
<img width="2093" alt="image" src="https://user-images.githubusercontent.com/26844/185119831-eb858dc2-0c2c-4993-8ac7-63989b73a0c2.png">

**Comment by chelsey-g** [comment]
I went ahead and removed the width from the #main div. That seemed to be the only issue there. Should be all set now.
<img width="2275" alt="Screen Shot 2022-08-17 at 12 54 02 PM" src="https://user-images.githubusercontent.com/97612806/185197978-2c22e536-6a7f-49f1-823d-4b3c4da095de.png">
