### ISSUE TITLE
add playlist page

### ISSUE THREAD

**Issue by phishy** [chelsey-g/spotify-clone#9]
- [x] add links for left nav playlists
- [x] add a function to spotify.js to fetch data for a specific playlist
- [x] add a new playlists route
- [ ] make a new playlists page
- [x] fetch data for playlist and render it in a view
- [ ] fix track #'s
- [ ] add hover track menu button
- [x] remove additional 0 from duration time in Track
<img width="336" alt="image" src="https://user-images.githubusercontent.com/26844/185639699-39357ad0-a6ba-4ef4-9ffc-558e998e0708.png">

**Comment by phishy** [comment]
@chelsey-g What's the status on this ticket? Once you get a PR raised, I can review it.

**Comment by chelsey-g** [comment]
I have two more tasks to complete before I say this issue is 100% completed. Once completed, I will create a branch and send it your way for review. We have reviewed most of these tasks for this issue together this past week.

**Comment by phishy** [comment]
Totally understand. Just introducing you to the wonderful world of GitHub issues. I love me some checkboxes!

**Comment by phishy** [comment]
I would like to take an account of what is left, as it's almost time to move on to another page in order to reinforce these lessons.
